spring:
  application:
    name: system-service
  cloud:
    nacos:
      server-addr: 121.40.138.25:8848
      discovery:
        group: xuecheng-plus-project
        namespace: dev
      config:
        refresh-enabled: true
        file-extension: yaml
        namespace: dev
        group:  xuecheng-plus-project
        extension-configs:
          - data-id: system-service-${spring.profiles.active}.yaml
            group: xuecheng-plus-project
            refresh: true
  profiles:
    active: dev